using Microsoft.Playwright;
using Xunit;

namespace IntelliMed.Tests.Ui;

// Covers the SMTP settings / user-invite / email-template feature added to Clinic Settings,
// User Management, and the new Email Templates admin pages. Deliberately does not attempt a real
// SMTP send (no live mail server available in this environment) — that path was verified manually
// against a disposable Ethereal Email test account. These tests only assert on UI/DB-backed
// behavior that doesn't depend on external network access, matching the rest of this suite.
[Collection("Playwright UI")]
public class EmailInfrastructureTests
{
    private readonly PlaywrightServerFixture _fixture;

    public EmailInfrastructureTests(PlaywrightServerFixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public async Task ClinicSettings_ShowsEmailSmtpSection()
    {
        var page = await _fixture.NewAuthenticatedPageAsync();
        await page.GotoAsync("/clinic-settings");
        await page.GetByRole(AriaRole.Heading, new() { Name = "Clinic Settings" }).WaitForAsync();

        await Assertions.Expect(page.GetByText("Email (SMTP)")).ToBeVisibleAsync();
        await Assertions.Expect(page.GetByLabel("Enable email sending")).ToBeVisibleAsync();
        await Assertions.Expect(page.GetByLabel("Use SSL/TLS")).ToBeVisibleAsync();
        await Assertions.Expect(page.GetByRole(AriaRole.Button, new() { Name = "Send Test Email" })).ToBeVisibleAsync();
    }

    [Fact]
    public async Task ClinicSettings_SavingSmtpHost_Persists()
    {
        var page = await _fixture.NewAuthenticatedPageAsync();
        await page.GotoAsync("/clinic-settings");
        await page.GetByRole(AriaRole.Heading, new() { Name = "Clinic Settings" }).WaitForAsync();

        var host = $"smtp-{Guid.NewGuid():N}.example.com";
        await page.Field("SMTP Host").FillAsync(host);
        await page.GetByRole(AriaRole.Button, new() { Name = "Save Changes" }).ClickAsync();
        await Assertions.Expect(page.GetByText("Clinic settings updated successfully.")).ToBeVisibleAsync();

        await page.ReloadAsync();
        await page.GetByRole(AriaRole.Heading, new() { Name = "Clinic Settings" }).WaitForAsync();
        await Assertions.Expect(page.Field("SMTP Host")).ToHaveValueAsync(host);
    }

    [Fact]
    public async Task SendTestEmailModal_OpensWithMessagePrefilled()
    {
        var page = await _fixture.NewAuthenticatedPageAsync();
        await page.GotoAsync("/clinic-settings");
        await page.GetByRole(AriaRole.Heading, new() { Name = "Clinic Settings" }).WaitForAsync();

        await page.GetByRole(AriaRole.Button, new() { Name = "Send Test Email" }).ClickAsync();

        await Assertions.Expect(page.Locator(".modal-title")).ToHaveTextAsync("Send Test Email");
        await Assertions.Expect(page.Field("Message")).ToHaveValueAsync("This is a test email");
        await Assertions.Expect(page.Field("Email Address")).ToHaveValueAsync("");
    }

    [Fact]
    public async Task UserManagement_CreateDialog_PasswordFieldIsReadOnlyAndAutoGenerated()
    {
        var page = await _fixture.NewAuthenticatedPageAsync();
        await page.GotoAsync("/admin/users");
        await page.GetByRole(AriaRole.Heading, new() { Name = "User Management" }).WaitForAsync();

        await page.GetByRole(AriaRole.Button, new() { Name = "Add User" }).ClickAsync();

        // The password field sits inside an .input-group (with a show/hide toggle button), so it's
        // not a direct sibling of its <label> — the generic Field() helper doesn't reach it.
        var passwordField = page.Locator(".modal-body input[type='password']");
        await Assertions.Expect(passwordField).ToBeVisibleAsync();

        var isReadOnly = await passwordField.EvaluateAsync<bool>("el => el.readOnly");
        Assert.True(isReadOnly, "The password field should be read-only — it's auto-generated, not typed by the admin.");

        var value = await passwordField.InputValueAsync();
        Assert.True(value.Length >= 8, "Auto-generated password should already be populated when the dialog opens.");
    }

    [Fact]
    public async Task UserManagement_CreatingUser_OffersSendInviteInModal()
    {
        var page = await _fixture.NewAuthenticatedPageAsync();
        await page.GotoAsync("/admin/users");
        await page.GetByRole(AriaRole.Heading, new() { Name = "User Management" }).WaitForAsync();

        await page.GetByRole(AriaRole.Button, new() { Name = "Add User" }).ClickAsync();
        await page.Field("First Name").FillAsync("Playwright");
        await page.Field("Last Name").FillAsync("Invitee");
        await page.Field("Email Address").FillAsync($"pw-invitee-{Guid.NewGuid():N}@example.com");

        await page.GetByRole(AriaRole.Button, new() { Name = "Create User" }).ClickAsync();

        await Assertions.Expect(page.GetByText("Playwright Invitee created successfully")).ToBeVisibleAsync();
        await Assertions.Expect(page.Locator(".modal-footer").GetByRole(AriaRole.Button, new() { Name = "Send Invite" })).ToBeVisibleAsync();

        await page.GetByRole(AriaRole.Button, new() { Name = "Done" }).ClickAsync();
        await Assertions.Expect(page.GetByText("Playwright Invitee")).ToBeVisibleAsync();
        await Assertions.Expect(page.GetByText("Pending")).ToBeVisibleAsync();
    }

    [Fact]
    public async Task EmailTemplateList_ShowsSeededDefaultTemplates()
    {
        var page = await _fixture.NewAuthenticatedPageAsync();
        await page.GotoAsync("/admin/email-templates");
        await page.GetByRole(AriaRole.Heading, new() { Name = "Email Templates" }).WaitForAsync();

        await Assertions.Expect(page.GetByText("Default Invite Email")).ToBeVisibleAsync();
        await Assertions.Expect(page.GetByText("Default Forgot Password")).ToBeVisibleAsync();
        await Assertions.Expect(page.GetByText("Invite Email", new() { Exact = true })).ToBeVisibleAsync();
        await Assertions.Expect(page.GetByText("Forgot Password", new() { Exact = true })).ToBeVisibleAsync();
    }

    [Fact]
    public async Task EmailTemplateEdit_LoadsRichEditorAndSavesSubjectChange()
    {
        var page = await _fixture.NewAuthenticatedPageAsync();
        await page.GotoAsync("/admin/email-templates");
        await page.GetByRole(AriaRole.Heading, new() { Name = "Email Templates" }).WaitForAsync();

        await page.Locator("tr", new PageLocatorOptions { HasTextString = "Default Forgot Password" })
            .GetByRole(AriaRole.Link, new() { Name = "Default Forgot Password" })
            .ClickAsync();

        await page.WaitForURLAsync(url => url.Contains("/admin/email-templates/edit/"));
        await Assertions.Expect(page.GetByRole(AriaRole.Combobox).First).ToHaveValueAsync("ForgotPassword");
        await Assertions.Expect(page.GetByRole(AriaRole.Button, new() { Name = "Bold (Ctrl+B)" })).ToBeVisibleAsync();
        await Assertions.Expect(page.GetByRole(AriaRole.Button, new() { Name = "Insert image" })).ToBeVisibleAsync();

        var newSubject = $"Reset your password ({Guid.NewGuid():N})";
        await page.Field("Subject").FillAsync(newSubject);
        await page.GetByRole(AriaRole.Button, new() { Name = "Save" }).ClickAsync();

        await page.WaitForURLAsync(url => url.EndsWith("/admin/email-templates"));
        await Assertions.Expect(page.GetByText(newSubject)).ToBeVisibleAsync();
    }

    [Fact]
    public async Task ForgotPassword_Submitting_ShowsGenericSuccessMessage()
    {
        var page = await _fixture.NewPageAsync();
        await page.GotoAsync("/forgot-password");
        await page.WaitForSelectorAsync("text=Forgot Password");

        await page.GetByPlaceholder("name@clinic.com").FillAsync("nonexistent-user@example.com");
        await page.GetByRole(AriaRole.Button, new() { Name = "Send Reset Link" }).ClickAsync();

        await Assertions.Expect(page.GetByText("If that account exists, a password reset email has been sent.")).ToBeVisibleAsync();
    }

    [Fact]
    public async Task SetPassword_WithoutTokenInUrl_ShowsInvalidLinkMessage()
    {
        var page = await _fixture.NewPageAsync();
        await page.GotoAsync("/set-password");
        await page.WaitForSelectorAsync("text=Set Your Password");

        await Assertions.Expect(page.GetByText("This link is invalid.")).ToBeVisibleAsync();
        await Assertions.Expect(page.GetByRole(AriaRole.Link, new() { Name = "Request a New Link" })).ToBeVisibleAsync();
    }
}
